name: "Release and Deploy"
on:
  push:
    branches:
      - "master"

jobs:
  release-and-deploy: 
    runs-on: "ubuntu-22.04"
    steps: 
      - name: "Checkout code"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Set up Node environment"
        uses: "actions/setup-node@v2"
        with:
          node-version: '16'
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Set up git user email"
        run: "git config --global user.email 'maciej.laciak@gmail.com'"
      - name: "Set up git user name" 
        run: "git config --global user.name 'mstream'"
      - name: "Create a GitHub release"
        run: "npm run release -- --ci"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Bundle web application"
        run: "npm run bundle"
      - name: "Deploy to GitHub Pages"
        uses: "peaceiris/actions-gh-pages@v3"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./static"

